# cloudbuild.yaml
substitutions:
  _PROJECT_ID: "gen-lang-client-0486914658"
  _LOCATION: "us-central1"
  _REPO: "legal-docs-repo"
  _IMAGE: "legal-docs-service"
  _TAG: "latest"
  _SERVICE: "legal-docs-service"

timeout: "1200s"

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${_TAG}'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${_TAG}'
    waitFor: ['Build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    id: 'Deploy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE}'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${_TAG}'
      - '--region'
      - '${_LOCATION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    waitFor: ['Push']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${_TAG}'
