# This file tells Google Cloud Build how to deploy the AI researcher.
steps:
# Step 1: Deploy the Cloud Function
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'gcloud'
  args:
  - 'functions'
  - 'deploy'
  - 'autonomous-researcher'
  - '--gen2'
  - '--runtime=python311'
  - '--region=us-central1'
  - '--source=.'
  - '--entry-point=autonomous_researcher.main'
  - '--trigger-http'
  - '--allow-unauthenticated'
  - '--timeout=540s'
  - '--memory=512MB'
  - '--set-env-vars=CLOUD_SQL_CONNECTION_NAME=${_SQL_INSTANCE_CONNECTION_NAME},GCP_PROJECT_ID=${PROJECT_ID}'
  - '--set-secrets=GEMINI_API_KEY=GEMINI_API_KEY:latest,DB_PASSWORD=DB_PASSWORD:latest,DB_USER=DB_USER:latest,DB_NAME=DB_NAME:latest'

# Step 2: Update the underlying Cloud Run service to add Cloud SQL connection
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'services'
  - 'update'
  - 'autonomous-researcher'
  - '--region=us-central1'
  - '--add-cloudsql-instances=${_SQL_INSTANCE_CONNECTION_NAME}'

# Default values for our variables.
substitutions:
  _SQL_INSTANCE_CONNECTION_NAME: 'gen-lang-client-0486914658:us-central1:legal-docs-db'

# This section tells Cloud Build where to put the logs.
options:
  logging: CLOUD_LOGGING_ONLY
