# The instruction manual for Google Cloud Build to deploy your site.
# This is the final, corrected version with the logging fix.
steps:
  # Step 1: Build the container image using the Dockerfile.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/law-depository-service:$COMMIT_SHA', '.']

  # Step 2: Push the container image to Google's Artifact Registry.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/law-depository-service:$COMMIT_SHA']

  # Step 3: Deploy the new container image to Cloud Run.
  - name: 'gcr.io/google-appengine/exec-wrapper'
    args:
      - '-i'
      - 'gcr.io/$PROJECT_ID/law-depository-service:$COMMIT_SHA'
      - '-s'
      - '${_SERVICE_NAME}'
      - '--'
      - 'gcloud'
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/law-depository-service:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=GCP_PROJECT_ID=$PROJECT_ID'
      - '--set-secrets=GEMINI_API_KEY=gemini-api-key:latest'

# This section stores the built container image.
images:
  - 'gcr.io/$PROJECT_ID/law-depository-service:$COMMIT_SHA'

# This is the crucial fix for the error you encountered.
# It tells Cloud Build to use the standard cloud logging service.
options:
  logging: CLOUD_LOGGING_ONLY

# These are variables that can be easily changed.
substitutions:
  _SERVICE_NAME: 'law-depository-service'
  _REGION: 'us-central1'

