# cloudbuild.yaml — final version for GitHub
# This file is configured to use Secret Manager for DB_USER (recommended).
# Usage (manual trigger):
# gcloud builds submit --config cloudbuild.yaml \
#   --substitutions=_SERVICE_NAME=legal-docs-service,_REGION=us-central1,_PROJECT_ID=gen-lang-client-0486914658,_REPOSITORY=legal-docs-repo,_IMAGE_TAG=latest,_SECRET_NAME=legal-docs-db-user

steps:
# --------------------------------------------------
# Step 0: Build & push image
# --------------------------------------------------
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/app:${_IMAGE_TAG}', '.' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/app:${_IMAGE_TAG}' ]

# --------------------------------------------------
# Step 1: Remove any existing DB_USER mapping (safe — ignores errors)
# --------------------------------------------------
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -euo pipefail
      echo "Cleaning old DB_USER mappings (secrets or env)"
      gcloud run services update "${_SERVICE_NAME}" --platform managed --region "${_REGION}" --project "${_PROJECT_ID}" --remove-secrets DB_USER || true
      gcloud run services update "${_SERVICE_NAME}" --platform managed --region "${_REGION}" --project "${_PROJECT_ID}" --remove-env-vars DB_USER || true

# --------------------------------------------------
# Step 2: Set DB_USER from Secret Manager
# --------------------------------------------------
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -euo pipefail
      if [ -z "${_SECRET_NAME}" ]; then
        echo "ERROR: _SECRET_NAME must be provided" >&2
        exit 1
      fi
      gcloud run services update "${_SERVICE_NAME}" --platform managed --region "${_REGION}" --project "${_PROJECT_ID}" --set-secrets DB_USER=${_SECRET_NAME}:latest

# --------------------------------------------------
# Step 3: Deploy the service
# --------------------------------------------------
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -euo pipefail
      gcloud run deploy "${_SERVICE_NAME}" \
        --image "us-central1-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/app:${_IMAGE_TAG}" \
        --region "${_REGION}" --platform managed --project "${_PROJECT_ID}" \
        --quiet

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: 'legal-docs-service'
  _REGION: 'us-central1'
  _PROJECT_ID: 'gen-lang-client-0486914658'
  _REPOSITORY: 'legal-docs-repo'
  _IMAGE_TAG: 'latest'
  _SECRET_NAME: 'legal-docs-db-user'

# ---------------------------------------------------------------------
# Guidance:
# - This config always sets DB_USER from Secret Manager.
# - Ensure the secret named in _SECRET_NAME exists.
# - Grant the Cloud Build service account roles/run.admin and roles/secretmanager.secretAccessor.
# - Replace default substitutions if needed in your Cloud Build trigger settings.
