# This file defines the automated build and deployment process on Google Cloud.
steps:
  # 1. Build the Docker container image.
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/legal-docs-repo/app:latest'
      - '.'

  # 2. Push the container image to Google Artifact Registry.
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/legal-docs-repo/app:latest'

  # 3. Deploy the new image to Cloud Run.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'legal-docs-service' # This is the name of your web service.
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/legal-docs-repo/app:latest'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      # --- THIS IS THE FIX ---
      # We are now pointing to the correct database instance name: 'legal-docs-db'.
      - '--add-cloudsql-instances'
      - '${PROJECT_ID}:${_REGION}:legal-docs-db' 
      - '--set-env-vars=DB_USER=postgres,DB_NAME=law_depository,INSTANCE_CONNECTION_NAME=${PROJECT_ID}:${_REGION}:legal-docs-db'
      # Securely attach your secrets (API key and database password).
      - '--set-secrets=GEMINI_API_KEY=GEMINI_API_KEY:latest,DB_PASSWORD=DB_PASSWORD:latest'

# Default region for deployment.
substitutions:
  _REGION: 'us-central1'

# The final image that was built and pushed.
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/legal-docs-repo/app:latest'

