# This file tells Google Cloud Build how to deploy the AI researcher.
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'functions'
  - 'deploy'
  - 'autonomous-researcher'
  - '--gen2'
  - '--runtime=python311'
  - '--region=us-central1'
  - '--source=.'
  - '--entry-point=main'
  - '--trigger-http'
  - '--allow-unauthenticated'
  - '--timeout=540s'
  - '--set-env-vars=CLOUD_SQL_CONNECTION_NAME=${_SQL_INSTANCE_CONNECTION_NAME},GCP_PROJECT_ID=${PROJECT_ID},GEMINI_SECRET_NAME=gemini-api-key'
  - '--set-sql-instance=${_SQL_INSTANCE_CONNECTION_NAME}'

substitutions:
  _SQL_INSTANCE_CONNECTION_NAME: 'gen-lang-client-0486914658:us-central1:legal-docs-db'

options:
  logging: CLOUD_LOGGING_ONLY
