# This file tells Google Cloud Build how to create the AI researcher as a background job.
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/legal-docs-repo/autonomous-researcher:${COMMIT_SHA}',
    '-f', 'Dockerfile.researcher',
    '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/legal-docs-repo/autonomous-researcher:${COMMIT_SHA}']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'jobs'
    - 'replace'
    - 'cloudrun-job.yaml'
    - '--region=us-central1'

options:
  logging: CLOUD_LOGGING_ONLY
