# This file defines a reusable, automated build and deployment process.
# It uses substitutions to avoid hardcoding names and regions.
steps:
# Step 1: Build the container image using Docker.
# The image tag uses the short Git commit SHA for versioning.
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  args:
    - 'build'
    - '-t'
    - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
    - '.'

# Step 2: Push the container image to Google Artifact Registry.
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push'
  args:
    - 'push'
    - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'

# Step 3: Deploy to Cloud Run.
# This single, idempotent step handles service creation and updates.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - '${_SERVICE_NAME}'
    - '--image'
    - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
    - '--region'
    - '${_REGION}'
    - '--platform'
    - 'managed'
    # Securely attaches secrets as a single, comma-separated string.
    - '--update-secrets'
    - 'GEMINI_API_KEY=GEMINI_API_KEY:latest,DB_PASSWORD=DB_PASSWORD:latest,DB_USER=DB_USER:latest,DB_NAME=DB_NAME:latest,DB_HOST=DB_HOST:latest'
    # Connects the service to the Cloud SQL database instance.
    - '--add-cloudsql-instances'
    - '${_SQL_INSTANCE_CONNECTION_NAME}'
    # This creates the environment variable your Python code needs to identify Cloud Run.
    - '--set-env-vars=CLOUD_SQL_CONNECTION_NAME=${_SQL_INSTANCE_CONNECTION_NAME}'

# Define the image to be pushed to Artifact Registry.
images:
- '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'

# Default substitution values. These can be overridden by the trigger or command line.
substitutions:
  _SERVICE_NAME: 'legal-docs-service'
  _REGION: 'us-central1'
  _REPOSITORY: 'legal-docs-repo'
  _SQL_INSTANCE_CONNECTION_NAME: 'gen-lang-client-0486914658:us-central1:legal-docs-db'

# Set logging options for the build process.
options:
  logging: CLOUD_LOGGING_ONLY

# This file tells Google Cloud Build how to deploy the AI researcher.
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - 'functions'
  - 'deploy'
  - 'autonomous-researcher'
  - '--gen2'
  - '--runtime=python311'
  - '--region=us-central1'
  - '--source=.'
  - '--entry-point=main'
  - '--trigger-http'
  - '--allow-unauthenticated'
  - '--timeout=540s'
  - '--set-env-vars=CLOUD_SQL_CONNECTION_NAME=${_SQL_INSTANCE_CONNECTION_NAME}'
  - '--add-cloudsql-instances=${_SQL_INSTANCE_CONNECTION_NAME}'

# Default values for our variables.
substitutions:
  _SQL_INSTANCE_CONNECTION_NAME: 'gen-lang-client-0486914658:us-central1:legal-docs-db'

# --- ADD THESE TWO LINES AT THE END ---
options:
  logging: CLOUD_LOGGING_ONLY
