# This file tells Google Cloud Build how to deploy the AI researcher.
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'functions'
  - 'deploy'
  - 'autonomous-researcher'
  - '--gen2'
  - '--runtime=python311'
  - '--region=us-central1'
  - '--source=.'
  - '--entry-point=main'
  - '--trigger-http'
  - '--allow-unauthenticated'
  - '--timeout=540s'
  # This section gives the function the right permissions to access the database and secrets
  - '--run-service-account'
  - '${_SERVICE_ACCOUNT}'
  - '--ingress-settings'
  - 'all'

# Default values for our variables.
substitutions:
  _SERVICE_ACCOUNT: 'gen-lang-client-0486914658@appspot.gserviceaccount.com'

# This section tells Cloud Build where to put the logs.
options:
  logging: CLOUD_LOGGING_ONLY
