# This file defines the automated build and deployment process.
# It runs every time you push a change to your GitHub repository.

steps:
# Step 1: Build the container image using Docker
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/legal-docs-repo/app:latest', '.']
  id: 'Build'

# Step 2: Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/legal-docs-repo/app:latest']
  id: 'Push'

# Step 3: THE FIX - This is the new, crucial step.
# It cleans up any old environment variables that might conflict with our new secret-based ones.
# It will ignore errors if the variables don't already exist.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Clean-Old-Variables'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud run services update legal-docs-service --region us-central1 --remove-env-vars=GEMINI_API_KEY,DB_PASSWORD,DB_USER,DB_NAME,DB_HOST --quiet || true

# Step 4: Deploy the container image to Cloud Run with the correct secret configuration.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'legal-docs-service' # Your service name
    - '--image'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/legal-docs-repo/app:latest'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--quiet'
    # This securely attaches all your secrets to the application.
    # --update-secrets is used to safely add or modify the secret mappings.
    - '--update-secrets'
    - |
      GEMINI_API_KEY=GEMINI_API_KEY:latest,
      DB_PASSWORD=DB_PASSWORD:latest,
      DB_USER=DB_USER:latest,
      DB_NAME=DB_NAME:latest,
      DB_HOST=DB_HOST:latest
    # This connects your service to the Cloud SQL database instance.
    - '--add-cloudsql-instances'
    - 'gen-lang-client-0486914658:us-central1:legal-docs-db' # Your DB connection name
    # This makes your service publicly accessible.
    - '--allow-unauthenticated'

# Define the image to be pushed to Artifact Registry
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/legal-docs-repo/app:latest'

# Set logging options for the build process
options:
  logging: CLOUD_LOGGING_ONLY

