services:
  - type: web
    name: global-insolvency-depository
    env: python
    plan: free # Specifies the free instance type
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/health
    envVars:
      - fromGroup: gemini-api # You still need to set this on Render
