services:
  - type: web
    name: lawdepository-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - fromGroup: gemini-api # Connects the environment group